# file: C:\Users\matth\AppData\Roaming\Python\Python313\site-packages\_pytest\_py\error.py
# hypothesis_version: 6.131.22

[267, 'P', 'R', 'UnknownErrno%d', '[{}]: {}', '_', '__doc__', '__module__', 'errno', 'py.error', 'win32', '{}.{} {!r}: {} ']